require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-rails
  - rubocop-performance
  - rubocop-packaging

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/*
    - test/dummy/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

########### METRICS ###############

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  Max: 30

## MINITEST
Minitest/MultipleAssertions:
  Max: 5

## RAILS

Rails/InverseOf:
  Enabled: true
  Exclude:
    - app/models/storage_tables/attachment.rb